[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "catbook"
dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
version = {attr = "catbook.main.VERSION"}
dependencies = {file = ["requirements.txt"]}